title @s actionbar textures/advancement/billeysmellfish
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon billey:dropfishsword
tellraw @a {"rawtext":[{"translate":"chat.advancement.task","with":{"rawtext":[{"selector":"@s"},{"translate":"advancements.billey.smelly_fish"}]}}]}
tellraw @s {"rawtext":[{"text":"§9"},{"translate":"chat.billbetta8"}]}