give @p billey:cat_bottle 1
give @p billey:zcat_bottle 1
give @p billey:scat_bottle 1
give @p billey:wcat_bottle 1
give @p billey:pizzapiece 64
give @p billey:picklepet_fertilizer 64
give @p billey:swordfish 1
give @p billey:swordcooked 64
give @p billey:colorful_bottle 1
give @p billey:leather_pet_armor 1
give @p billey:golden_pet_armor 1
give @p billey:chain_pet_armor 1
give @p billey:iron_pet_armor 1
give @p billey:diamond_pet_armor 1
give @p billey:netherite_pet_armor 1
give @p billey:endrod_pet_armor 1
give @p billey:velvet_slime 16
give @p billey:hamster_ball 64
give @p billey:cooked_hamster 64
give @p billey:pet_hat 64
give @p billey:cooked_catfish 64
give @p billey:chocolate_catfish 64
give @p billey:golden_swordfish
give @p billey:sand_banana 64
give @p billey:yeet_duck 16
give @p billey:cooked_snail 64
give @p billey:cooked_snail_s 64
give @p billey:cooked_snail_w 64
give @p billey:snail_helmet 64
give @p billey:duck_hat 1
give @p billey:betta_fish 64
give @p billey:cooked_betta_fish 64
give @p billey:poultry_orange 64
give @p billey:fermented_mercat_milk 16
give @p billey:cooked_mergoose_tongue 64
give @p billey:shark_tooth_sword
give @p billey:charged_piranha_launcher
give @p billey:velvet_slime_block 64
give @p billey:blue_velvet_slime_block 64
give @p billey:mixed_velvet_slime_block 64